############## Notification door ####################
alias: 'Telegram bot send message if voordeur is open'
hide_entity: true
trigger:
    platform: state
    entity_id: binary_sensor.sensor_voordeur
    to: 'on'
condition:
    condition: and
    conditions:
       - condition: time
         after: '23:00:00'
         before: '07:00:00'
action:
    service: notify.telegram
    data:
      message: 'Voordeur is open!'