---
# Light platform Yeelight
# In this file I add al my yeelight lights, mayby in the future I will split this in rooms or levels.
#
# https://www.home-assistant.io/components/light.group/
#

- platform: yeelight
  devices:
    !secret yeelight_1:
      name: Vliering voor | Zolder (manual)
    !secret yeelight_2:
      name: Vliering achter | Zolder (manual)
