---
## Experimental sensor for home/away detection
- platform: 'bayesian'
  prior: 0.65
  name: 'Klaas Thuis'
  probability_threshold: 0.9
  observations:
    # Wifi
    - entity_id: device_tracker.19216802
      prob_given_true: 0.9
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'
    # Bluetooth
    # - entity_id: device_tracker.samsung_galaxy_s7_edge
    #  prob_given_true: 0.9
    #  prob_given_false: 0.3
    #  platform: 'state'
    #  to_state: 'home'
    ##### GPS #####
    # Life 360
    - entity_id: device_tracker.life360_klaas_schoute
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
