---
#
# https://www.home-assistant.io/components/binary_sensor.trend/
#
- platform: trend
  sensors:
    phone_battery_increase_klaas:
      entity_id: sensor.battery_phone_klaas
    phone_battery_decrease_klaas:
      entity_id: sensor.battery_phone_klaas
      invert: true
    phone_battery_increase_marlene:
      entity_id: sensor.battery_phone_marlene
    phone_battery_decrease_marlene:
      entity_id: sensor.battery_phone_marlene
      invert: true
