---
# The workday binary sensor indicates, whether the current day is a workday or not.
#
# https://www.home-assistant.io/components/binary_sensor.workday/
#

- platform: workday
  country: NL
  workdays: [ mon, tue, wed, thu, fri ]