---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control
custom_header: !include lovelace/cards/custom_header.yaml
swipe_nav: !include lovelace/cards/swipe_nav.yaml
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/ground_floor.yaml
  - !include lovelace/views/loft.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/temperatures.yaml
  - !include lovelace/views/automation.yaml
  - !include lovelace/views/system_information.yaml
