---
## LOVELACE UI ##

resources:
  - url: /local/plan-coordinates.js?v=2
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js

title: My Smart Home
views:
  ################################## Home ##################################
  - title: Home
    cards:
      # Wie is er thuis?
      - type: entity-filter
        title: Wie is thuis?
        entities:
          - device_tracker.samsunggalaxys7edgelan
          - device_tracker.19216825
          - device_tracker.ce10160afb463b3504
        state_filter:
          - home
        card:
          type: glance
          column_width: 30%
          title: Wie is thuis?
          show_state: false
          # show_name: false

      # Laat zien welke lampen aan staan in huis
      - type: entity-filter
        title: Welke lichten staan aan?
        entities:
          - entity: light.yeelight_ct2_7c49eb19d5f5
            tap_action: toggle
          - entity: light.yeelight_ct2_7c49eb19d785
            tap_action: toggle
          - entity: switch.lamp_slaapkamer__zolder
            tap_action: toggle
          - entity: switch.led_bureau__zolder
            tap_action: toggle
          - entity: switch.led_slaapkamer__zolder
            tap_action: toggle
          - entity: light.vliering_achter__zolder_auto
            tap_action: toggle
          - entity: light.vliering_voor__zolder_auto
            tap_action: toggle
          # - entity: switch
            # name: Hall
            # tap_action: toggle
        state_filter:
          - "on"
        card:
          type: glance
          title: Welke lichten staan aan?
          column_width: 50%
          show_state: false

      # Laat devices met een bijna lege batterij zien
      - type: entity-filter
        entities:
          - sensor.zwave_battery_front_door
          - sensor.zwave_battery_smoke_sensor_begane_grond
          - sensor.zwave_battery_smoke_sensor_slaapkamer_zolder
        state_filter:
          - "20"
          - "10"
          - "0"
        show_empty: false
        card:
          type: glance
          title: Batterij bijna leeg
          column_width: 30%

      # Philips TV
      - type: media-control
        entity: media_player.32pfs640212

      # Google home mini - slaapkamer
      - type: media-control
        entity: media_player.slaapkamer_zolder__mini

      # Google home mini - woonkamer
      - type: media-control
        entity: media_player.woonkamer__mini

      # Device tracker kaart
      - type: map
        entities:
          - zone.home
          - zone.huis_marlene
          - zone.schiphol_airport
          - zone.school
          - zone.station_alkmaar
          - device_tracker.ce10160afb463b3504

      # Agenda
      - type: "custom:calendar-card"
        name: "Agenda"
        showProgressBar: true
        entities:
          - calendar.agenda_marlene
          - calendar.feestdagen_in_nederland
          - calendar.prive_agenda
          - calendar.rooster_klaas

  ################################## Begane grond ##################################
  - title: Begane grond
    cards:
      # Toont sensors in de trappengang
      - type: entities
        title: Trappengang | Begane grond
        entities:
          - sensor.fibaro__smoke_sensor__gang_begane_grond_temperature

      # Laat zien of voordeur openstaat en wat de temperatuur is
      - type: entities
        title: Hal | Begane grond
        entities:
          - binary_sensor.sensor_voordeur
          - sensor.fibaro__door_sensor__hal_begane_grond_temperature

  ################################## Eerste verdieping ##################################
  - title: Eerste verdieping
    cards:

  ################################## Zolder ##################################
  - title: Zolder
    cards:
      # Overzicht temperatuur en computer status
      - type: glance
        title: Slaapkamer
        entities:
          - entity: switch.computer_klaas
            tap_action: toggle
          - entity: sensor.fibaro__smoke_sensor__slaapkamer_zolder_temperature
        column_width: 50%

      # Toont lampen in de slaapkamer
      - type: entities
        title: Slaapkamer lampen
        show_header_toggle: false
        entities:
          - switch.lamp_slaapkamer__zolder
          - switch.led_bureau__zolder
          - switch.led_slaapkamer__zolder

      # Toont lampen op de vliering
      - type: entities
        title: Vliering
        entities:
          - light.yeelight_ct2_7c49eb19d5f5
          - light.yeelight_ct2_7c49eb19d785

      # Een grafiek van de temperatuur op de slaapkamer
      - type: history-graph
        title: Temperatuur grafiek
        hours_to_show: 168
        refresh_interval: 3600
        entities:
          - sensor.fibaro__smoke_sensor__slaapkamer_zolder_temperature

  ################################## Tuin ##################################
  - title: Tuin
    cards:
      # Apparaten in de tuin
      - type: entities
        title: Tuin
        show_header_toggle: false
        entities:
          - switch.fibaro__wall_plug_1_switch

  ################################## Temperaturen in huis ##################################
  - icon: mdi:temperature-celsius
    title: Temperaturen grafiek
    cards:
      # Toont met een grafiek de temperaturen in huis
      - type: history-graph
        hours_to_show: 168
        refresh_interval: 3600
        entities:
          - entity: sensor.fibaro__smoke_sensor__gang_begane_grond_temperature
            name: Trappengang | begane grond
          - entity: sensor.fibaro__door_sensor__hal_begane_grond_temperature
            name: Hal | begane grond
          - entity: sensor.fibaro__smoke_sensor__slaapkamer_zolder_temperature
            name: Slaapkamer | zolder
        column_width: 50%

      # Toont de temperaturen in huis
      - type: entities
        title: Temperaturen in huis
        entities:
          - sensor.fibaro__smoke_sensor__gang_begane_grond_temperature
          - sensor.fibaro__door_sensor__hal_begane_grond_temperature
          - sensor.fibaro__smoke_sensor__slaapkamer_zolder_temperature

  ################################## Automatisering ##################################
  - icon: mdi:home-automation
    title: Automatisering
    cards:
      # Toont alle automatiseringen
      - type: entities
        title: Automatisering
        entities:
          - group.automatisering_view

  ################################## Systeeminformatie ##################################
  - icon: mdi:server
    title: Systeeminformatie
    cards:
      # Toont sensoren van de raspberry pi
      - type: entities
        title: Prestaties
        entities:
          - sensor.processor_use
          - sensor.memory_use_percent
          - sensor.cpu_temperature
          - binary_sensor.cpu_high
          - binary_sensor.cpu_hot

      # Toont informatie van home assistant
      - type: entities
        title: Home Assistant Info
        entities:
          - sensor.last_boot
          - sensor.ha_uptime
          - sensor.ha_installed_version
          - sensor.python_version
          - updater.updater
          - sensor.bad_login

      # Toont informatie over het geheugen op de raspberry pi
      - type: entities
        title: Opslag
        entities:
          - sensor.disk_use_percent_
          - sensor.disk_free_
          - sensor.homeassistant_v2db
          - sensor.homeassistantlog
          - sensor.ozw_logtxt
          - sensor.configurationyaml

      # Toont informatie over de netwerk verbinding
      - type: entities
        title: Netwerk
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.myipopendnscom
          - sensor.ssl_certificate_expiry

      # Toont de batterij percentages van de Z-wave devices
      - type: glance
        title: Batterij Percentages
        column_width: 30%
        entities:
          - sensor.zwave_battery_front_door
          - sensor.zwave_battery_smoke_sensor_begane_grond
          - sensor.zwave_battery_smoke_sensor_slaapkamer_zolder
