---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control
resources: !include_dir_list lovelace/resources
cch:
  menu: show
  notifications: clock
  voice: hide
  options: show
  clock_format: 24
  clock_am_pm: false
  clock_date: false
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        menu: overflow
        notifications: overflow
        swipe: true
        swipe_animate: swipe
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/ground_floor.yaml
  - !include lovelace/views/loft.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/temperatures.yaml
  - !include lovelace/views/automation.yaml
  - !include lovelace/views/system_information.yaml
