---
################# LOW Battery warning #####################
# Battery Low Alert - Front Door
- alias: 'Battery Low Alert - Front Door'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_front_door
    below: 10
    for:
      seconds: 30
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de voordeur sensor is bijna leeg, Percentage: {{ states.sensor.zwave_battery_front_door.state }}%'

# Battery Low Alert - Smoke sensor | begane grond     
- alias: 'Battery Low Alert - Smoke sensor | begane grond'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_smoke_sensor_begane_grond
    below: 10
    for:
      seconds: 30
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de rookmelder op de begane grond is bijna leeg, Percentage: {{ states.sensor.zwave_battery_smoke_sensor_begane_grond.state }}%'

# Battery Low Alert - Smoke sensor | kamer zolder     
- alias: 'Battery Low Alert - Smoke sensor | kamer zolder'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_smoke_sensor_slaapkamer_zolder
    below: 10
    for:
      seconds: 30
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de rookmelder op kamer zolder is bijna leeg, Percentage: {{ states.sensor.zwave_battery_smoke_sensor_slaapkamer_zolder.state }}%'
