---
################################## Automatisering ##################################
id: automation
icon: mdi:home-automation
title: Automatisering
path: automations
cards:
  # Notify
  - type: custom:monster-card
    card:
      type: entities
      title: Notify Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.notify*
      exclude:
        - entity_id: automation.notify_fibaro*

  # Telegram
  - type: custom:monster-card
    card:
      type: entities
      title: Telegram Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.telegram*

  # System
  - type: custom:monster-card
    card:
      type: entities
      title: System Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.system*

  # House
  - type: custom:monster-card
    card:
      type: entities
      title: House Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.house*

  # People
  - type: custom:monster-card
    card:
      type: entities
      title: People Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.people*
