---
#
# Give me a TTS notification when my phone is full charged
# And only if I am home and it is before midnight
#
- alias: House - Notify when phone is fully charged
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.battery_phone_klaas
      value_template: '{{ states.sensor.battery_phone_klaas.state }}'
      above: 99
      for: '00:03:00'
  condition:
    - condition: state
      entity_id: 'binary_sensor.klaas_thuis'
      state: 'on'
    - condition: time
      before: '23:59:00'
      after: '08:00:00'
  action:
    - service: tts.google_say
      entity_id: media_player.slaapkamer_zolder_mini
      data:
        message: 'Je telefoon is 100% opgeladen'
