---
# Als ik van school naar huis ga stuur dan een bericht hoelaat ik thuis kom.
- alias: '[People] - Travel from school to home'
  trigger:
    - platform: zone
      entity_id: device_tracker.ba52ad3a0d208bdc
      zone: zone.hogeschool_leiden
      event: leave
  condition:
    - condition: time
      after: '11:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
    - condition: zone
      entity_id: device_tracker.ba52ad3a0d208bdc
      zone: zone.station_leiden
  action:
    - service: notify.telegram_klaas
      data:
        message: 'Klaas is onderweg naar huis vanaf Leiden en in Alkmaar om: {{ states.sensor.leiden_alkmaar.attributes.arrival_time_actual }} via de route: {{ states.sensor.leiden_alkmaar.attributes.route }}.'
