---
################################################
## Packages System
################################################

homeassistant:
  customize_glob:
    weblink.*:
      icon: mdi:web

  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Input Text
    ################################################
    input_text.github_message:
      <<: *customize
      icon: mdi:pencil

    ################################################
    ## Binary Sensor
    ################################################

    # binary_sensor.db_large:
    #   <<: *customize
    #   friendly_name: Database groot

    binary_sensor.home_assistant:
      <<: *customize
      friendly_name: Home Assistant status

    ################################################
    ## Sensor
    ################################################

    sensor.processor_use:
      <<: *customize
      friendly_name: Processorgebruik

    sensor.memory_use_percent:
      <<: *customize
      friendly_name: Geheugengebruik

    sensor.disk_free:
      <<: *customize
      friendly_name: Beschikbare opslag

    sensor.disk_use_percent:
      <<: *customize
      friendly_name: Gebruikte opslag

    sensor.home_assistant_v2_db:
      <<: *customize
      friendly_name: Home Assistant Database

    sensor.home_assistant_log:
      <<: *customize
      friendly_name: Home Assistant Logbestand

    sensor.ozw_log_txt:
      <<: *customize
      friendly_name: Home Assistant OZW Logbestand

    sensor.configuration_yaml:
      <<: *customize
      friendly_name: Home Assistant Configuration

    sensor.cpu_temperature:
      <<: *customize
      friendly_name: Processortemperatuur

    sensor.myip:
      <<: *customize
      friendly_name: Publiek IP-adres
      icon: mdi:network

    sensor.ha_runtime:
      <<: *customize
      friendly_name: Uptime sinds laatste start HA
      icon: mdi:clock

    sensor.ha_installed_version:
      <<: *customize
      friendly_name: Hassio geinstalleerde versie

    sensor.python_version:
      <<: *customize
      friendly_name: Python geinstalleerde versie

    sensor.klaasnicolaas_smarthome_homeassistant_config_last_build_duration:
      <<: *customize
      hidden: true

    sensor.klaasnicolaas_smarthome_homeassistant_config_last_build_id:
      <<: *customize
      hidden: true

    sensor.klaasnicolaas_smarthome_homeassistant_config_last_build_started_at:
      <<: *customize
      hidden: true

    sensor.klaasnicolaas_smarthome_homeassistant_config_state:
      <<: *customize
      hidden: true

    sensor.last_boot:
      <<: *customize
      friendly_name: Laatste (re)boot Intel Nuc

    ################################################
    ## Script
    ################################################

    script.host_reboot:
      <<: *customize
      icon: mdi:rotate-3d-variant
      can_cancel: false
      friendly_name: Reboot Intel NUC

    script.hassio_reboot:
      <<: *customize
      icon: mdi:rotate-3d-variant
      can_cancel: false
      friendly_name: Restart Home Assistant

    script.host_shutdown:
      <<: *customize
      icon: mdi:power
      can_cancel: false
      friendly_name: Shutdown Intel NUC

    script.backup_now:
      <<: *customize
      icon: mdi:backup-restore
      can_cancel: false
      friendly_name: Make Snapshot

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      cpu_high:
        value_template: '{{ states.sensor.processor_use.state | float > 80 }}'
        friendly_name: 'CPU hoog'
  - platform: template
    sensors:
      cpu_hot:
        value_template: '{{ states.sensor.cpu_temperature.state | float > 70 }}'
        friendly_name: 'CPU heet'
  ##### Uptime robot
  - platform: uptimerobot
    api_key: !secret uptime_robot_key
################################################
## Sensor
################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: last_boot
      - type: swap_use_percent
  - platform: command_line
    name: CPU Temperature
    command: "/bin/cat /sys/class/thermal/thermal_zone2/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: filesize
    file_paths:
      # - !secret filesize_homeassistant_db
      - !secret filesize_homeassistant_log
      - !secret filesize_ozw_log
      - !secret filesize_configuration
  - platform: dnsip
  ##### When will the SSL expiry
  - platform: cert_expiry
    host: !secret cert_expiry_host
  ##### Latest HA installed version
  - platform: version
    name: HA Installed Version
    scan_interval: 86400
  ##### Latest python3 version
  - platform: command_line
    name: Python Version
    command: python3 --version
    scan_interval: 86400
  ##### Github
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: 'klaasnicolaas/Smarthome-homeassistant-config'
  ##### UpTime
  - platform: uptime
    name: Time Online
  ##### MariaDB Size
  - platform: sql
    db_url: !secret mariadb_addon
    queries:
      - name: DB size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="HA_Recorder" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB
  ##### Restart time
  - platform: command_line
    name: HA Restart Time
    command: "/bin/cat /config/home-assistant.log | /bin/grep 'Home Assistant initialized in' | /usr/bin/awk '{print $10}' | /bin/sed 's/[^0-9.]//g'"
    scan_interval: 60
    unit_of_measurement: "sec"

################################################
## Input boolean
################################################

input_boolean:
  maintenance_mode:
    name: Onderhouds Mode
    icon: mdi:auto-fix

################################################
## Alert
################################################

alert:
  cpu_high:
    name: Gebruik CPU is hoog
    entity_id: binary_sensor.cpu_high
    state: 'on'
    repeat: 5  # minutes
    can_acknowledge: true
    skip_first: false
    notifiers:
      - telegram_klaas

  cpu_hot:
    name: Temperatuur CPU is hoog
    entity_id: binary_sensor.cpu_hot
    state: 'on'
    repeat: 120  # minutes
    can_acknowledge: true
    skip_first: false
    notifiers:
      - telegram_klaas

  # db_large:
  # name: Database Large
  # entity_id: binary_sensor.db_large
  # state: 'on'
  # repeat: # minutes
  # - 15
  # - 30
  # - 60
  # - 120
  # can_acknowledge: true
  # skip_first: false
  # notifiers:
  # - telegram_klaas

  maintenance_mode_alert:
    name: Onderhouds Mode staat al aan voor een lange tijd
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - telegram_klaas

################################################
## Script
################################################

script:
  hassio_reboot:
    alias: Hassio Reboot
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: homeassistant.restart

  host_reboot:
    alias: Host Reboot
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: hassio.host_reboot

  backup_now:
    alias: New Snapshot
    sequence:
      - delay: 00:00:02
      - service: automation.trigger
        entity_id: automation.system_make_weekly_hassio_backup

  host_shutdown:
    alias: Host Shutdown
    sequence:
      - delay: 00:00:02
      - service: hassio.host_shutdown

################################################
## Notify
################################################

notify:
  - name: telegram_klaas
    platform: telegram
    chat_id: !secret telegram_chat_id_klaas
