---
# Custom icons for the house automations
automation.house_deurbel_melding_niet_thuis:
  icon: mdi:bell-ring-outline
automation.house_deurbel_melding_wel_thuis:
  icon: mdi:bell-ring-outline
automation.house_turn_on_pc_when_arrive:
  icon: mdi:power
