---
# Custom icons for the system automations
automation.system_perform_system_checks:
  icon: mdi:eye-check-outline
automation.system_make_weekly_hassio_backup:
  icon: mdi:cloud-upload-outline
automation.system_set_ha_theme:
  icon: mdi:theme-light-dark
