---
- alias: '[Telegram] - Bot that reply pong to ping'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    service: notify.telegram
    data:
      message: 'pong'
