---
# Give a notification if there is a beta update, but not equal to that of the stable.
- alias: '[Notify] - Beta version'
  trigger:
    - platform: state
      entity_id: sensor.hassio_beta_versie
  condition:
    - condition: template
      value_template: "{{ states('sensor.hassio_stable_versie') != states('sensor.hassio_beta_versie') }}"
  action:
    - service: notify.telegram_klaas
      data_template:
        title: Upgrade time!
        message: >-
          'Beta update beschikbaar voor Hass.io!'
          'Versie: {{ states('sensor.hassio_beta_versie') }} is zojuist gereleased.'
