---
################# LOW Battery warning #####################
# Battery Low Alert - Front Door
- alias: '[Notify] - Battery Low Alert - Front Door'
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_front_door
    below: 15
    for: "00:00:30"
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de voordeur sensor is bijna leeg, Percentage: {{ states.sensor.zwave_battery_front_door.state }}%'

# Battery Low Alert - Smoke sensor | begane grond
- alias: '[Notify] - Battery Low Alert - Smoke sensor | begane grond'
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_smoke_sensor_begane_grond
    below: 15
    for: "00:00:30"
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de rookmelder op de begane grond is bijna leeg, Percentage: {{ states.sensor.zwave_battery_smoke_sensor_begane_grond.state }}%'

# Battery Low Alert - Smoke sensor | kamer zolder
- alias: '[Notify] - Battery Low Alert - Smoke sensor | kamer zolder'
  trigger:
    platform: numeric_state
    entity_id: sensor.zwave_battery_smoke_sensor_slaapkamer_zolder
    below: 15
    for: "00:00:30"
  action:
    service: notify.telegram_klaas
    data:
      message: 'Batterij van de rookmelder op kamer zolder is bijna leeg, Percentage: {{ states.sensor.zwave_battery_smoke_sensor_slaapkamer_zolder.state }}%'
