---
# Nederlandse Spoorwegen #
- platform: nederlandse_spoorwegen
  api_key: !secret ns_api_key
  routes:
    - name: Alkmaar - Leiden
      from: Amr
      to: Ledn
    - name: Leiden - Alkmaar
      from: Ledn
      to: Amr
    - name: Schiphol Airport - Leiden
      from: Shl
      to: Ledn
    - name: Leiden - Schiphol Airport
      from: Ledn
      to: Shl
