---
#
#
- platform: template
  sensors:
    ha_uptime:
      friendly_name: 'HA Uptime'
      value_template: >-
        {% if states('sensor.time_online') == '0.0' %} 
          Just restarted...
        {% else %}
          {% macro phrase(value, name) %}
          {%- set value = value | int %}
          {%- set end = 's' if value > 1 else '' %}
          {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
          {%- endmacro %}
          
          {% set weeks = (states('sensor.time_online') | int / 7) | int %}
          {% set days = (states('sensor.time_online') | int) - (weeks * 7) %}
          {% set hours = (states('sensor.time_online') | float - states('sensor.time_online') | int) * 24 %}
          {% set minutes = (hours - hours | int) * 60 %}

          {{ [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') }}
        {% endif %}
