---
# Enables a custom component called "versions".
# It is a sensor that fetches the version number of current Home Assistant releases.
#
# https://www.home-assistant.io/components/version/
#
########## BETA ##########
# Fetch beta version of HA
- platform: version
  name: Hassio Beta versie
  beta: true
  image: intel-nuc
  source: hassio

# HassOS version beta
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/beta.json
  name: HassOs version - beta
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version beta
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/beta.json
  name: Supervisor version - beta
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600

########## STABLE ##########
# Fetch stable version of HA
- platform: version
  name: Hassio Stable versie
  beta: false
  image: intel-nuc
  source: hassio

# HassOS version stable
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: HassOs version - stable
  value_template: "{{ value_json.hassos.ova }}"
  scan_interval: 3600

# Supervisor version stable
- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: Supervisor version - stable
  value_template: "{{ value_json.supervisor }}"
  scan_interval: 3600
