---
# Als er op de deurbel word gedrukt, stuur dan een telegram bericht en als we thuis zijn ook een spraak bericht.
- alias: House - Deurbel Melding Wel Thuis
  initial_state: true
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
  condition:
    - condition: state
      entity_id: binary_sensor.klaas_thuis
      state: 'on'
  action:
    # Play a thing dong sound through the speakers
    - service: media_player.play_media
      data:
        entity_id: media_player.slaapkamer_zolder__mini
        media_content_id: !secret play_ding_dong
        media_content_type: 'audio/mp3'
    # Play a thing dong sound through the speakers
    - service: media_player.play_media
      data:
        entity_id: media_player.slaapkamer_zolder__mini
        media_content_id: !secret play_ding_dong
        media_content_type: 'audio/mp3'
    - delay: '00:00:01'
    # Play a typed text through the speakers
    - service: tts.google_say
      entity_id: media_player.slaapkamer_zolder__mini
      data:
        message: 'Er staat iemand bij de voordeur'
        cache: true
    # Play a typed text through the speakers
    - service: tts.google_say
      entity_id: media_player.woonkamer__mini
      data:
        message: 'Er staat iemand bij de voordeur'
        cache: true
