---
#
# If you press the doorbell, send a telegram message when we are not at home.
#
- alias: '[House] - Deurbel Melding Niet Thuis'
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
  condition:
    - condition: state
      entity_id: binary_sensor.klaas_thuis
      state: 'off'
  action:
    - service: notify.telegram_klaas
      data:
        title: Deurbel
        data:
          photo:
            - url: http://tiptag.com.ar/wp-content/uploads/2018/06/timbre1.jpg
    - service: notify.telegram_klaas
      data:
        title: Deurbel
        message: 'Ding dong! Iemand staat voor de deur!'
