---
#
# If you press the doorbell, let it know via the google home speakers.
#
- alias: House - Deurbel Melding Wel Thuis
  initial_state: true
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"entity_id": "switch.deurbel"}
  condition:
    - condition: state
      entity_id: binary_sensor.klaas_thuis
      state: 'on'
  action:
    # Play a thing dong sound through the speakers
    - service: media_player.play_media
      data:
        entity_id: media_player.slaapkamer_zolder_mini
        media_content_id: !secret play_ding_dong
        media_content_type: 'audio/mp3'
    # Play a thing dong sound through the speakers
    - service: media_player.play_media
      data:
        entity_id: media_player.slaapkamer_zolder_mini
        media_content_id: !secret play_ding_dong
        media_content_type: 'audio/mp3'
    - delay: '00:00:01'
    # Play a typed text through the speakers
    - service: tts.google_say
      entity_id: media_player.slaapkamer_zolder_mini
      data:
        message: 'Er staat iemand bij de voordeur'
        cache: true
    # Play a typed text through the speakers
    - service: tts.google_say
      entity_id: media_player.woonkamer_mini
      data:
        message: 'Er staat iemand bij de voordeur'
        cache: true
