---
# Als ik thuis kom en mijn pc staat nog uit, zet hem dan aan.
- alias: House - Turn on pc when arrive
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.klaas_status
      from: 'Weg'
      to: 'Net Aangekomen'
    - platform: state
      entity_id: sensor.klaas_status
      from: 'Lang Weg'
      to: 'Net Aangekomen'
  condition:
    - condition: state
      entity_id: switch.computer_klaas
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.computer_klaas
